--PREGUNTA 1
-- ENUNCIADO A: ES TABLA SUGERENCIA
-- ENUNCIADO B: LA TABLA SUGERENCIA, ESTA SIN EL PREFIJO 'L3' Y ESTA EN SINGULAR
-- ADEMAS SU PRIMARY KEY SE LLAMA SOLAMENTE ID, DEBERIA SER ID_SUGERENCIAS

--ENUNCIADO C

ALTER TABLE SUGERENCIA RENAME TO L3_SUGERENCIAS;

ALTER TABLE L3_SUGERENCIAS RENAME COLUMN ID TO ID_SUGERENCIAS;

--PREGUNTA 2

-- CREAR UN CAMPO FECHA_VIGENTE EN L3_PRODUCTOS
-- LUEGO UNA TABLA L3_HISTICO_PRECIOS_PRODUCTO
-- CON CAMPOS ID_HISTORICO,ID_PRODUCTO,PRECIO_ANTERIOR,PRECIO_NUEVO,
--FECHA_INICIO_VIGENCIA,FECHA_FIN VIGENCIA

ALTER TABLE L3_PRODUCTOS ADD FECHA_VIGENTE DATE;

CREATE TABLE L3_HISTORICO_PRECIOS_PRODUCTOS (
    ID_HISTORICO NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    PRECIO_ANTERIOR NUMERIC(8,2) NOT NULL,
    PRECIO_NUEVO NUMERIC(8,2) NOT NULL,
    FECHA_INICIO_VIGENCIA DATE NOT NULL,
    FECHA_FIN_VIGENCIA DATE NOT NULL
);

ALTER TABLE  L3_HISTORICO_PRECIOS_PRODUCTOS 
ADD CONSTRAINT PK_ID_HISTORICO PRIMARY KEY(ID_HISTORICO);

ALTER TABLE  L3_HISTORICO_PRECIOS_PRODUCTOS 
ADD CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
REFERENCES L3_PRODUCTOS(ID_PRODUCTO);


--PREGUNTA 3

CREATE TABLE L3_CLIENTES(
    CLIENTE_ID NUMBER NOT NULL, 
    TIPO_CLIENTE_ID NUMBER,
    NOMBRE VARCHAR2(100), 
    APELLIDO VARCHAR2(100),
    EMAIL VARCHAR2(100),
    TELEFONO VARCHAR2(20), 
    CODIGO_PUCP VARCHAR2(20)
);

ALTER TABLE  L3_CLIENTES
ADD CONSTRAINT PK_CLIENTE_ID PRIMARY KEY(CLIENTE_ID);

--ENUNCIADO A: BOTA ERROR, YA QUE LA CLIENTE_ID ES PRIMARY KEY EN LA TABLA
-- POR LO TANTO, ES UNICO Y AL QUERER INSERTAR UN NUEVO CLIENTE 
-- CON ESTE ID_CLIENTE EXISTENTE, EL MOTOR NO LO PERMITE.

--ENUNCIADO B: AL ANALIZAR EL SCRIPT_3 CREA UNA FUNCION LLAMADA SEQ_CLIENTE
--ESTE DEVUELVE NUMEROS SECUENCIALES LA FUNCION A USAR EL SEQ_CLIENTES.NEXTVAL

--ENUNCIADO C:AL USAR MANUELMENTE DEBEMOS CONOCER PREVIAMENTE EL VALOR DE PK
-- PARA PODER INSERTAR UN DATO, LO CUAL PUEDE SER INEFICIENTE. POR LO TANTO,
-- UTILIZAR UNA SECUENCIA EVITAS CONSULTA,CALCULOS PREVIOS Y DUPLICADOS.

--ENUNCIADO D: AL VOLVER A INSERTAR LOS DATOS DEL SCRIPT_4 INSERTA LOS DATOS 
-- CORRECTAMENTA, YA QUE LA SECUENCIA AUMENTO HASTA 15 Y AL VOLVER A USAR 
-- EL SCRIPT LA SECUENCIA LLEGA HASTA 20.

--ENUNCIADO E: SE PUEDE OBSERVAR QUE SE CREA UNA SECUENCIA LLAMADA 'SEQ_CLIENTES'
--QUE EMPIEZA EN 11 Y INCREMENTA EN 1 SU VALOR SIN VALOR MAX DEFINIDO 
-- Y SIN REINICIAR SU CICLO EN CASO TENGA UN LIMITE. LO QUE PERMITE CREAR LLAVES
--PRIMARIAS AUTOINCREMENTADAS POR MEDIO DE SEQ_CLIENTES.NEXTVAL.

--PREGUNTA 5:

SELECT 
    l3_productos.CODIGO_PRODUCTO,
    l3_productos.NOMBRE AS "NOMBRE_LIBRO",
    L3_LIBROS.ISBN ,
    L3_EDITORIALES.NOMBRE AS "EDITORIAL",
    L3_EDITORIALES.PAIS_ORIGEN ,
    L3_EDITORIALES.CONTACTO_NOMBRE 
FROM 
    L3_PRODUCTOS
JOIN 
    L3_LIBROS l ON L3_PRODUCTOS.PRODUCTO_ID = L3_LIBROS.PRODUCTO_ID
JOIN 
    L3_EDITORIALES e ON L3_PRODUCTOS.EDITORIAL_ID = L3_EDITORIALES.EDITORIAL_ID
WHERE 
    L3_PRODUCTOS.PRECIO_BASE > 100
    AND L3_PRODUCTOS.ESTADO = 'ACTIVO'
    AND EXISTS (
        SELECT 1 
        FROM L3_LIBROS 
        WHERE PRODUCTO_ID = L3_PRODUCTOS.PRODUCTO_ID
    )
ORDER BY 
    L3_PRODUCTOS.NOMBRE ASC;
    
SELECT 
    L3_PEDIDO_ESPECIALES.PEDIDO_ESPECIAL_ID ,
    L3_PEDIDO_ESPECIALES.FECHA_SOLICITUD,
    L3_PEDIDO_ESPECIALES.ESTADO,
    L3_CLIENTES.NOMBRE || ' ' || L3_CLIENTES.APELLIDO AS "NOMBRE_COMPLETO",
    L3_CLIENTES.EMAIL,
    L3_CLIENTES.TELEFONO
FROM 
    L3_PEDIDOS_ESPECIALES
JOIN 
    L3_CLIENTES c ON L3_PEDIDO_ESPECIALES.CLIENTE_ID = L3_CLIENTES.CLIENTE_ID
WHERE 
    TO_CHAR(L3_PEDIDO_ESPECIALES.FECHA_SOLICITUD, 'YYYY') = '2024'
    AND L3_PEDIDO_ESPECIALES.MONTO_ADELANTO > 200
ORDER BY 
    L3_PEDIDO_ESPECIALES.FECHA_SOLICITUD ASC;
