--PREGUNTA 1

CREATE TABLE ET_USUARIO(
    ID_USUARIO NUMBER NOT NULL,
    USUARIO VARCHAR2(30)NOT NULL,
    CLAVE VARCHAR2(30)NOT NULL,
    ESTADO CHAR(1) NOT NULL
);

ALTER TABLE ET_USUARIO ADD CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO);

--PREGUNTA 2

COMMENT ON COLUMN ET_USUARIO.ID_USUARIO IS 'Identificador del usuario.';

COMMENT ON COLUMN ET_USUARIO.USUARIO IS 'Nombre del usuario.';

COMMENT ON COLUMN ET_USUARIO.CLAVE IS 'Clave o contraseña';

COMMENT ON COLUMN ET_USUARIO.ESTADO IS 'A:  activo,I:inactivo';

--PREGUNTA 3

CREATE TABLE ET_ROL(
    ID_ROL NUMBER NOT NULL,
    NOMBRE VARCHAR2(30)NOT NULL
);

ALTER TABLE ET_ROL ADD CONSTRAINT PK_ID_ROL PRIMARY KEY(ID_ROL);

--PREGUNTA 4

COMMENT ON COLUMN ET_ROL.ID_ROL IS 'Identificador del rol';

COMMENT ON COLUMN ET_ROL.NOMBRE IS 'Nombre del rol.';

--PREGUNTA 5

ALTER TABLE ET_USUARIO ADD ID_ROL NUMBER NOT NULL;

--PREGUNTA 6

ALTER TABLE ET_USUARIO ADD CONSTRAINT FK_ID_ROL FOREIGN KEY(ID_ROL)
REFERENCES ET_ROL(ID_ROL);

--PREGUNTA 7

INSERT INTO ET_ROL(ID_ROL,NOMBRE) VALUES (1,'Admin');

INSERT INTO ET_ROL(ID_ROL,NOMBRE) VALUES (2,'Conductor');

INSERT INTO ET_ROL(ID_ROL,NOMBRE) VALUES (3,'Boleteria');

--PREGUNTA 8

INSERT INTO ET_USUARIO(ID_USUARIO,USUARIO,CLAVE,ESTADO,ID_ROL)
VALUES (1,'aangeles','1234','A',1);

INSERT INTO ET_USUARIO(ID_USUARIO,USUARIO,CLAVE,ESTADO,ID_ROL)
VALUES (2,'dpaz','1234','A',2);

INSERT INTO ET_USUARIO(ID_USUARIO,USUARIO,CLAVE,ESTADO,ID_ROL)
VALUES (3,'jpauca','1234','A',2);

INSERT INTO ET_USUARIO(ID_USUARIO,USUARIO,CLAVE,ESTADO,ID_ROL)
VALUES (4,'ldiaz','1234','A',3);

INSERT INTO ET_USUARIO(ID_USUARIO,USUARIO,CLAVE,ESTADO,ID_ROL)
VALUES (5,'elozano','1234','A',3);

--PREGUNTA 9

ALTER TABLE ET_TICKET RENAME COLUMN ID_TICKET_VIAJE TO ID_TICKET;

ALTER TABLE ET_TURNO RENAME COLUMN ID_TURNO_VIAJE TO ID_TURNO;

--PREGUNTA 10

ALTER TABLE ET_CONDUCTOR MODIFY (
    APELLIDO_PATERNO VARCHAR2(50),
    APELLIDO_MATERNO VARCHAR2(50)
);

ALTER TABLE ET_MODELO_BUS MODIFY (
    FABRICANTE VARCHAR2(100)
);

--PREGUNTA 11

UPDATE et_bus
SET ESTADO='M'
WHERE ID_BUS=5
;

--PREGUNTA 12

UPDATE ET_MODELO_BUS
SET FABRICANTE = 'Mercedes Benz'
WHERE FABRICANTE = 'Mercedes'
;

--PREGUNTA 13

SELECT * FROM ET_CONDUCTOR
WHERE TIPO_LICENCIA='A-IIIa'
;

--PREGUNTA 14

SELECT * FROM ET_BUS
WHERE PLACA LIKE 'M%'
;

SELECT * FROM ET_PARADERO
WHERE ID_DISTRITO IN (
    SELECT ID_DISTRITO FROM ET_DISTRITO
    WHERE NOMBRE='MIRAFLORES'
);
