--PREGUNTA 1

CREATE TABLE BS_CARGO(
    IDCARGO NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(30 BYTE) NOT NULL,
    SUELDO NUMERIC (6, 2) NOT NULL,
    IND_TIEMPO_COMPLETO CHAR(1 BYTE) NOT NULL
);

ALTER TABLE BS_CARGO ADD CONSTRAINT PK_IDCARGO PRIMARY KEY (IDCARGO);

--PREGUNTA 2

COMMENT ON COLUMN BS_CARGO.IDCARGO IS 'Identificador del cargo.';
COMMENT ON COLUMN BS_CARGO.DESCRIPCION IS 'Nombre del cargo.';
COMMENT ON COLUMN BS_CARGO.SUELDO IS 'Monto que gana según el cargo.';
COMMENT ON COLUMN BS_CARGO.IND_TIEMPO_COMPLETO IS 'Indicador si es tiempo completo: Si (S) o No (N)';

--PREGUNTA 3

ALTER TABLE BS_EMPLEADO ADD IDCARGO NUMBER NOT NULL;

ALTER TABLE BS_EMPLEADO ADD FECHA_FIN_CONTRATO DATE;

ALTER TABLE BS_TIENDA ADD DIRECCION VARCHAR(250 BYTE) NOT NULL;

ALTER TABLE BS_DETALLE_ORDEN ADD COSTO NUMBER(6,2) NOT NULL;

--PREGUNTA 4

ALTER TABLE BS_EMPLEADO ADD CONSTRAINT FK_IDCARGO FOREIGN KEY (IDCARGO) 
REFERENCES BS_CARGO(IDCARGO);

--PREGUNTA 5

ALTER TABLE BS_PERSONA MODIFY (
    PRIMERAPELLIDO VARCHAR(50),
    SEGUNDOAPELLIDO VARCHAR(50)
);

-- PREGUNTA 6

ALTER TABLE BS_GUIASASTRERIA MODIFY(IDCLIENTE CHAR(6));

ALTER TABLE BS_GUIASASTRERIA ADD CONSTRAINT FK_IDCLIENTE FOREIGN KEY (IDCLIENTE)
REFERENCES BS_CLIENTE(IDCLIENTE);

--PREGUNTA 7

INSERT INTO bs_cargo(IDCARGO,descripcion,SUELDO,IND_TIEMPO_COMPLETO) 
VALUES(1,'Administrador',3500,'S');

INSERT INTO bs_cargo(IDCARGO,descripcion,SUELDO,IND_TIEMPO_COMPLETO) 
VALUES(2,'Vendedor',3000,'S');

INSERT INTO bs_cargo(IDCARGO,descripcion,SUELDO,IND_TIEMPO_COMPLETO) 
VALUES(3,'Sastre',2500,'N');

INSERT INTO bs_cargo(IDCARGO,descripcion,SUELDO,IND_TIEMPO_COMPLETO) 
VALUES(4,'Asistente',2700,'S');

--Pregunta 8

--SELECT * FROM bs_categoria;


INSERT INTO BS_CATEGORIA(idcategoria,descripcion,estado) 
VALUES ('010','Uniformes','A');

INSERT INTO BS_CATEGORIA(idcategoria,descripcion,estado) 
VALUES ('011','Abrigos','A');

--PREGUNTA 9

--ELIMINO LOS DATOS DE PRENDAS ASOCIADOS A CATEGORIA INACTIVAS

DELETE FROM BS_PRENDA WHERE idcategoria IN (
SELECT IDCATEGORIA FROM BS_CATEGORIA
WHERE ESTADO='I'
);

DELETE FROM  BS_CATEGORIA WHERE ESTADO = 'I';

--PREGUNTA 10

DELETE FROM BS_PERSONA
WHERE IDPERSONA LIKE 'CLI%' AND (FECHANACIMIENTO IS NULL OR CELULAR=999999999)
;

--PREGUNTA 11

SELECT * FROM BS_PERSONA
WHERE PRIMERAPELLIDO LIKE '%De%'
OR PRIMERAPELLIDO LIKE '%de%'
OR SEGUNDOAPELLIDO LIKE '%De%'
OR SEGUNDOAPELLIDO LIKE '%de%'
OR SEGUNDOAPELLIDO IS NULL
;

-- COINCIDE PERO NO MUESTRA LOS DOS ULTIMOS PORQUE LOS ELIMINE EN LA PREGUNTA ANTERIOR

--PREGUNTA 12

SELECT DESCRIPCION FROM BS_PRENDA
WHERE IDCATEGORIA IN (SELECT IDCATEGORIA FROM BS_CATEGORIA
    WHERE DESCRIPCION='Moda casual' -- IDCATEGORIA IN (1,2,4,5,10,11)
) AND COLOR='negro'
;



