--Pregunta 1 
CREATE TABLE BS_CARGO(
    IDCARGO NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(30) NOT NULL,
    SUELDO NUMERIC(6,2) NOT NULL,
    IND_TIEMPO_COMPLETO CHAR(1) NOT NULL
);

ALTER TABLE BS_CARGO ADD CONSTRAINT PK_CARGO PRIMARY KEY(IDCARGO);

--Pregunta 2
COMMENT ON COLUMN BS_CARGO.IDCARGO IS 'Identificador del cargo';
COMMENT ON COLUMN BS_CARGO.DESCRIPCION IS 'Nombre del cargo';
COMMENT ON COLUMN BS_CARGO.SUELDO IS 'Monto que gana según el cargo';
COMMENT ON COLUMN BS_CARGO.IND_TIEMPO_COMPLETO IS 'Indicador si es tiempo 
completo: Si(S) o No(N)';


--Pregunta 3
ALTER TABLE BS_EMPLEADO ADD IDCARGO NUMBER NOT NULL;
ALTER TABLE BS_EMPLEADO ADD FECHA_FIN_CONTRATO DATE;

ALTER TABLE BS_TIENDA ADD DIRECCION VARCHAR2(250) NOT NULL;

ALTER TABLE BS_DETALLE_ORDEN ADD COSTO NUMBER(6,2) NOT NULL;

--Pregunta 4
ALTER TABLE BS_EMPLEADO ADD CONSTRAINT FK_CARGO FOREIGN KEY(IDCARGO)
    REFERENCES BS_CARGO(IDCARGO);
    
--Pregunta 5 
ALTER TABLE BS_PERSONA MODIFY(PRIMERAPELLIDO VARCHAR2(50), 
    SEGUNDOAPELLIDO VARCHAR2(50));
    
    
--Pregunta 6 
ALTER TABLE BS_GUIASASTRERIA MODIFY (IDCLIENTE CHAR(6));
ALTER TABLE BS_GUIASASTRERIA ADD CONSTRAINT FK_CLIENTE FOREIGN KEY(IDCLIENTE)
    REFERENCES BS_CLIENTE(IDCLIENTE);
    
--Pregunta 7
INSERT INTO BS_CARGO (IDCARGO, DESCRIPCION, SUELDO, IND_TIEMPO_COMPLETO)
    VALUES (1,'Administrador', 3500,'S');
INSERT INTO BS_CARGO (IDCARGO, DESCRIPCION, SUELDO, IND_TIEMPO_COMPLETO)
    VALUES (2,'Vendedor', 3000,'S');
INSERT INTO BS_CARGO (IDCARGO, DESCRIPCION, SUELDO, IND_TIEMPO_COMPLETO)
    VALUES (3,'Sastre', 2500,'N');
INSERT INTO BS_CARGO (IDCARGO, DESCRIPCION, SUELDO, IND_TIEMPO_COMPLETO)
    VALUES (4,'Asistente', 2700,'S');
    

--Pregunta 8
SELECT * FROM BS_CATEGORIA;
INSERT INTO BS_CATEGORIA (IDCATEGORIA, DESCRIPCION, ESTADO) VALUES ('010', 'Uniformes', 'A');
INSERT INTO BS_CATEGORIA (IDCATEGORIA, DESCRIPCION, ESTADO) VALUES ('011', 'Abrigos', 'A');


--Pregunta 9
DELETE FROM BS_PRENDA
WHERE IDCATEGORIA IN (SELECT IDCATEGORIA FROM BS_CATEGORIA 
WHERE ESTADO = 'I');

DELETE FROM BS_CATEGORIA
WHERE ESTADO = 'I';


--PREGUNTA 10
DELETE FROM BS_PERSONA
WHERE IDPERSONA LIKE 'CLI%'  AND (FECHANACIMIENTO IS NULL OR CELULAR = 999999999);

--Pregunta 11
SELECT * FROM BS_PERSONA
WHERE PRIMERAPELLIDO LIKE '%de%' OR SEGUNDOAPELLIDO LIKE '%de%' OR 
SEGUNDOAPELLIDO IS NULL;

--Pregunta 12
SELECT DESCRIPCION FROM BS_PRENDA
WHERE IDCATEGORIA IN 
    (SELECT IDCATEGORIA FROM BS_CATEGORIA
    WHERE DESCRIPCION = 'Moda casual')
    AND COLOR = 'negro';
