-- Pregunta 1

CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER NOT NULL,
NOMBRE VARCHAR2(40),
APE_PATERNO VARCHAR2(40),
APE_MATERNO VARCHAR2(40),
ACTIVO CHAR(1)
);

--DROP TABLE EMPLEADO;

ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY(ID_EMPLEADO);

-- Pregunta 2

COMMENT ON COLUMN EMPLEADO.ID_EMPLEADO IS 'Identificador de empleado';

COMMENT ON COLUMN EMPLEADO.NOMBRE IS 'Nombre del empleado'; 

COMMENT ON COLUMN EMPLEADO.APE_PATERNO IS 'Apellido paterno del empleado'; 

COMMENT ON COLUMN EMPLEADO.APE_MATERNO IS 'Apellido materno del empleado'; 

COMMENT ON COLUMN EMPLEADO.ACTIVO IS 'Indicador si el empleado esta activo o no: Si(S) o No(N)'; 

--Pregunta 3

CREATE TABLE ROL(
ID_ROL NUMBER NOT NULL,
DESCRIPCION VARCHAR2(50) NOT NULL,
ES_JEFE CHAR(1) NOT NULL
);

ALTER TABLE ROL ADD CONSTRAINT PK_ID_ROL PRIMARY KEY (ID_ROL);

--PREGUNTA  4

COMMENT ON COLUMN ROL.ID_ROL IS 'Identificador del rol'; 
COMMENT ON COLUMN ROL.DESCRIPCION IS 'Descripcion del rol'; 
COMMENT ON COLUMN ROL.ES_JEFE IS 'Identificador de si el rol es jefe: Si(S) o No(N)'; 

--PREGUNTA 5

ALTER TABLE EMPLEADO ADD FECHA_FIN_CONTRATO DATE NOT NULL;
ALTER TABLE EMPLEADO ADD IDROL NUMBER NOT NULL;
ALTER TABLE ROL ADD ACTIVO CHAR(1) NOT NULL;
COMMENT ON COLUMN ROL.ACTIVO IS 'Identificador de si el rol está activo: Si (S) o No (N)';
ALTER TABLE CLIENTE ADD ACTIVO CHAR(1);
COMMENT ON COLUMN CLIENTE.ACTIVO IS 'Identificador de si el cliente está activo: Si (S) o No (N)';
ALTER TABLE SEDE ADD CODIGO_POSTAL VARCHAR2(6);
ALTER TABLE SEDE ADD ACTIVO CHAR(1);
COMMENT ON COLUMN SEDE.ACTIVO IS 'Identificador de si la sede está activa: Si (S) o No (N)';


--PREGUNTA 6

ALTER TABLE EMPLEADO ADD CONSTRAINT FK_ID_ROL FOREIGN KEY (IDROL) 
REFERENCES ROL(ID_ROL);

--PREGUNTA 7

ALTER TABLE CLIENTE MODIFY (
razon_social VARCHAR(80),
direccion_fiscal VARCHAR(120)
);

--PREGUNTA 8

ALTER TABLE FORMAPAGO RENAME COLUMN NOMBRE 
TO nombre_forma_pago;
ALTER TABLE SEDE RENAME COLUMN area 
TO area_sede;

--PREGUNTA 9

SELECT NOMBRESEDE,DISTRITO FROM SEDE
WHERE PROVINCIA = 'Lima' AND DISTRITO IN ('Villa El Salvador','Lurin')
;

--PREGUNTA 10

INSERT INTO ROL(id_rol,descripcion,es_jefe,activo) 
VALUES (1,'Administrador','S','S');
INSERT INTO ROL(id_rol,descripcion,es_jefe,activo) 
VALUES (2,'Almacenero','N','S');
INSERT INTO ROL(id_rol,descripcion,es_jefe,activo) 
VALUES (3,'Vendedor','N','S');
INSERT INTO ROL(id_rol,descripcion,es_jefe,activo) 
VALUES (4,'Jefe de Almacen','S','S');
INSERT INTO ROL(id_rol,descripcion,es_jefe,activo) 
VALUES (5,'Jefe de produccion','S','N');

--PREGUNTA 11

SELECT id_cliente,razon_social,telefono,correo,direccion_fiscal FROM CLIENTE
where ruc is null
;

--PREGUNTA 12
-- FORMA 1 POR CHATGPT
SELECT DISTINCT ID_CLIENTE, RAZON_SOCIAL, RUC
FROM cliente 
INNER JOIN ordenpedido  ON ID_CLIENTE = cliente_ID_CLIENTE
WHERE (DIRECCION_FISCAL LIKE '%Av%' OR RUC IS NULL);

-- FORMA 2
SELECT ID_CLIENTE, RAZON_SOCIAL, RUC FROM CLIENTE
WHERE EXISTS(
    SELECT cliente_id_cliente FROM ORDENPEDIDO
    WHERE cliente_id_cliente = ID_CLIENTE
) 
AND (DIRECCION_FISCAL LIKE '%Av%' OR RUC IS NULL)
ORDER BY RAZON_SOCIAL ASC
;

--FORMA 3
SELECT ID_CLIENTE, RAZON_SOCIAL, RUC 
FROM CLIENTE
WHERE ID_CLIENTE IN (SELECT CLIENTE_ID_CLIENTE FROM ORDENPEDIDO)
AND (DIRECCION_FISCAL LIKE '%Av%' OR RUC IS NULL)
;


--PREGUNTA 13
-- NO SALE IGUAL XD
SELECT area_sede,ID_SEDE,NOMBRESEDE,DISTRITO,PROVINCIA FROM SEDE
WHERE area_sede > 300 AND (provincia IN ('Lima') 
AND DISTRITO IN ('Villa El Salvador','Lurin')) -- COMENTA  ES LINEA O LA OTRA
-- AND (DISTRITO='Villa El Salvador' OR DISTRITO='Lurin')) 
--COMENTA UNA DE LAS 2 LINEAS
;



