--PREGUNTA 1 

CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER NOT NULL,
    NOMBRE VARCHAR2(40),
    APE_PATERNO VARCHAR2(40),
    APE_MATERNO VARCHAR2(40),
    ACTIVO CHAR(1)
);

ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO 
PRIMARY KEY (ID_EMPLEADO);

/

--PREGUNTA 2

COMMENT ON COLUMN EMPLEADO.ID_EMPLEADO IS 'Identificador de empleado';
COMMENT ON COLUMN EMPLEADO.NOMBRE IS 'Nombre empleado';
COMMENT ON COLUMN EMPLEADO.APE_PATERNO IS 'Apellido paterno del empleado';
COMMENT ON COLUMN EMPLEADO.APE_MATERNO IS 'Apellido materno del empleado';
COMMENT ON COLUMN EMPLEADO.ACTIVO IS 'Identificador si el empleado  esta activo o
 no: Si(S) o No (N)';
 

--PREGUNTA 3
CREATE TABLE ROL(
    ID_ROL NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(50) NOT NULL,
    ES_JEFE CHAR(1) NOT NULL
);

ALTER TABLE ROL ADD CONSTRAINT PK_ROL PRIMARY KEY(ID_ROL);


--PREGUNTA 4
COMMENT ON COLUMN ROL.ID_ROL IS 'Identificador de rol';
COMMENT ON COLUMN ROL.DESCRIPCION IS 'Decripcion de rol';
COMMENT ON COLUMN ROL.ES_JEFE IS 'Identificador de si rol es jefe: SI(S) o No(N)';

/
--PREGUNTA 5
ALTER TABLE EMPLEADO ADD FECHA_FIN_CONTRATO DATE NOT NULL;
ALTER TABLE EMPLEADO ADD IDROL NUMBER NOT NULL;

ALTER TABLE ROL ADD ACTIVO CHAR(1) NOT NULL ;
COMMENT ON COLUMN ROL.ACTIVO IS 'Identificador de si el rol esta activo: Si(S) o No(N)';

ALTER TABLE CLIENTE ADD ACTIVO CHAR(1);
COMMENT ON COLUMN CLIENTE.ACTIVO IS 'Identificador si el cliente esta activo:
 Si(S) o No(N)';

ALTER TABLE SEDE ADD CODIGO_POSTAL VARCHAR2(26);
ALTER TABLE SEDE ADD ACTIVO CHAR(1);
COMMENT ON COLUMN SEDE.ACTIVO IS 'Identificador de si la sede esta activa: 
 Si (S) o No(N)';
 
 
 --Pregunta 6
 ALTER TABLE EMPLEADO ADD CONSTRAINT FK_ROL FOREIGN KEY (IDROL)
    REFERENCES ROL(ID_ROL);
    
--Pregunta 7
ALTER TABLE CLIENTE MODIFY (RAZON_SOCIAL VARCHAR2(80), DIRECCION_FISCAL 
    VARCHAR2(120));

--Pregunta 8
ALTER TABLE FORMAPAGO RENAME COLUMN NOMBRE TO NOMBRE_FORMA_PAGO;
ALTER TABLE SEDE RENAME COLUMN AREA TO AREA_SEDE;

--Pregunta 9
SELECT * FROM  SEDE
WHERE PROVINCIA = 'Lima' and 
(DISTRITO = 'Lurin' OR DISTRITO = 'Villa El Salvador');

--Pregunta 10
INSERT INTO ROL (ID_ROL, DESCRIPCION, ES_JEFE, ACTIVO) VALUES 
    (1,'Administrador', 'S','S');
INSERT INTO ROL (ID_ROL, DESCRIPCION, ES_JEFE, ACTIVO) VALUES 
    (2,'Almacenero', 'N','S');
INSERT INTO ROL (ID_ROL, DESCRIPCION, ES_JEFE, ACTIVO) VALUES 
    (3,'Vendedor', 'N','S');
INSERT INTO ROL (ID_ROL, DESCRIPCION, ES_JEFE, ACTIVO) VALUES 
    (4,'Jefe de Almacen', 'S','S');
INSERT INTO ROL (ID_ROL, DESCRIPCION, ES_JEFE, ACTIVO) VALUES 
    (5,'Jefe de Produccion', 'S','N');
    

--Pregunta  11
SELECT ID_CLIENTE, RAZON_SOCIAL, TELEFONO, CORREO, DIRECCION_FISCAL FROM CLIENTE
WHERE RUC IS NULL;

--Pregunta 12
SELECT ID_CLIENTE, RAZON_SOCIAL, RUC FROM CLIENTE
WHERE ID_CLIENTE IN (SELECT DISTINCT CLIENTE_ID_CLIENTE FROM ORDENPEDIDO) AND
(DIRECCION_FISCAL LIKE '%Av%' OR RUC IS NULL);

--PREGUNTA 13

SELECT * FROM  SEDE
WHERE AREA_SEDE > 300 AND PROVINCIA = 'Lima' AND (DISTRITO = 'Villa El Salvador'
OR DISTRITO = 'Lurin');


